// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title IStylusValuator
/// @notice Interface to call the CollateralX Rust/Stylus valuation contract.
/// @dev Maps to the ABI auto-generated by stylus-sdk's #[public] macro.
///      The Stylus contract is deployed as a regular contract on Arbitrum
///      and is callable via standard EVM CALL opcode.
interface IStylusValuator {
    /// @notice Calculates the current depreciated & risk-adjusted value of an asset.
    /// @param assetType     Category of the asset (0=machinery, 1=vehicle, 2=real-estate, …)
    /// @param initialValue  Original purchase value in minor currency units (e.g. cents)
    /// @param purchaseDate  UNIX timestamp of the original purchase
    /// @param riskScore     Risk rating 0–100 (values >50 trigger additional 10% discount)
    /// @param currentTimestamp  The current block timestamp
    /// @return The risk-adjusted depreciated value as uint256
    function calculateCurrentValue(
        uint8 assetType,
        uint64 initialValue,
        uint64 purchaseDate,
        uint8 riskScore,
        uint64 currentTimestamp
    ) external view returns (uint256);

    /// @notice Batch-valuate multiple assets in a single call.
    function batchValuate(
        uint64[] calldata initialValues,
        uint64[] calldata purchaseDates,
        uint8[] calldata riskScores,
        uint64 currentTimestamp
    ) external view returns (uint256[] memory);

    /// @notice Returns a year-by-year depreciation schedule (year 0 through year 10).
    function getDepreciationSchedule(
        uint64 initialValue,
        uint8 riskScore
    ) external view returns (uint256[] memory);
}
